language: ruby
script: bundle exec rake spec
rvm:
 - 1.9.2
 - 1.9.3
 - jruby-18mode
 - jruby-19mode
 - rbx-18mode
 - rbx-19mode
 - 1.8.7
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
